<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>InventarioApp</AssemblyName>
    <RootNamespace>TechStore.Inventario</RootNamespace>
    <Version>1.0.0</Version>
    <Description>Módulo de control de inventario para TechStore SAS</Description>
  </PropertyGroup>

</Project>
